!
frr version 10.5.3
frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.0.1/31
exit
!
interface eth2
 ip address 192.168.2.1/24
exit
!
router bgp 65002
 bgp router-id 10.0.0.1
 neighbor 10.0.0.0 remote-as 65001
 !
 address-family ipv4 unicast
  neighbor 10.0.0.0 activate
  network 192.168.2.0/24
 exit-address-family
exit
!
end
