name: aegis-demo-01-two-pcs-and-a-switch-TESTSID1
topology:
  links:
  - endpoints:
    - pc-a:eth1
    - switch:eth1
  - endpoints:
    - pc-b:eth1
    - switch:eth2
  nodes:
    pc-a:
      exec:
      - apk add iproute2 iputils -q
      - ip link set eth1 up
      image: alpine:latest
      kind: linux
    pc-b:
      exec:
      - apk add iproute2 iputils -q
      - ip link set eth1 up
      image: alpine:latest
      kind: linux
    switch:
      exec:
      - apk add iproute2 iputils bridge-utils -q
      - ip link add name br0 type bridge
      - ip link set br0 up
      - ip link set eth1 up
      - ip link set eth1 master br0
      - ip link set eth2 up
      - ip link set eth2 master br0
      image: alpine:latest
      kind: linux
